### PR TITLE
Adding writeCartGrid_forGRDECL to class GeologyModel and calling it

### PR DESCRIPTION
**Pull request by mzakari31**
Hi here is a function to write cartesian grids at Eclipse GRDECL format and a notebook call to call it and test it

### CODE REVIEW

**Comment by BinWang0213** [comment]
Hi Mustapha,

Thanks for your contribution. I have a small suggestion to improve the performance:

```
from itertools import groupby
#https://stackoverflow.com/a/17238629
strs = "0.3 0.2 1.0 0.2 0.2 0.2 0.5 0.5"
new_str = ""
for k,v in groupby(strs.split()):
    group = list(v)
    #print(k,group,group[0])
    if(len(group)>1): new_str+=str(len(group)) + "*"
    new_str+=group[0] +" "

print(new_str)
0.3 0.2 1.0 3*0.2 2*0.5 
```

**Comment by mzakari31** [comment]
I accidently closed the PR.
Here is a new commit with your brilliant improvement. Thanks

**Comment by mzakari31** [comment]
Hi Bin,
I saw that you started to compute transmissibilities. I would like to be
able to solve the single phase pressure equation on corner point grids. I
wrote a single phase solver for  cartesian grids from mrst book.
 Can you please give me hints for developing a TPFA solver for CPG? I think
I need half transmissibilities for that?
Is it right?
Regards
Mustapha

**Comment by BinWang0213** [comment]
Hi Mustpha,

I didn't implement a flow solver for a CPG grid. I believe that is more complex than you expected.

I suggest you run such simulations using https://www.sintef.no/projectweb/mrst/

Thanks,
Bin

**Comment by mzakari31** [comment]
Hi Bin
Ok no problem. I am reading mrst source code Maybe I ll be able to have a
first python version ina few weeks.
Thanks

**Pull request merged**
